openapi: 3.0.3
info:
  title: API de Pasajeros
  description: API que combina GORM y SQL nativo para gestión de pasajeros
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /pasajeros-sql:
    get:
      summary: Listar pasajeros activos (SQL nativo)
      parameters:
        - name: limit
          in: query
          description: Cantidad de pasajeros por página
          required: false
          schema:
            type: integer
            default: 10
        - name: offset
          in: query
          description: Desplazamiento para paginación
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Lista de pasajeros activos
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pasajero'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      limit:
                        type: integer
                      offset:
                        type: integer
                      pages:
                        type: integer
  /pasajeros:
    post:
      summary: Crear nuevo pasajero (GORM)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasajeroInput'
      responses:
        '201':
          description: Pasajero creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pasajero'
  /pasajeros-sql/{id}:
    get:
      summary: Buscar pasajero por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pasajero encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pasajero'
        '404':
          description: Pasajero no encontrado
    put:
      summary: Activar pasajero
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pasajero activado correctamente
    delete:
      summary: Desactivar pasajero
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pasajero desactivado correctamente
components:
  schemas:
    Pasajero:
      type: object
      properties:
        id:
          type: string
        asiento:
          type: integer
        nombre:
          type: string
        activo:
          type: boolean
    PasajeroInput:
      type: object
      required:
        - asiento
        - nombre
      properties:
        asiento:
          type: integer
        nombre:
          type: string
